In [3]:
import numpy as np

In [2]:
arr = np.random.randint(-9,9,36).reshape(6,6)

In [3]:
arr

array([[ 5,  3,  3,  0, -8,  6],
       [ 4, -2,  6,  5, -7,  7],
       [-8,  6, -6,  2, -3, -9],
       [-9, -9, -6,  3, -1,  0],
       [-5,  8, -3,  6, -3, -5],
       [ 0, -9, -5,  6, -1,  5]])

Given a 6x6 2D Array 

There are 16 hourglasses in array, and an hourglass sum is the sum of an hourglass' values. 
Calculate the hourglass sum for every hourglass in array, then print the maximum hourglass sum.

In [22]:
sum = []
def hourglassSum(arr):
     
    for i in range(1,5):
        for j in range(1,5):
            print(i,j)
            sum.append(arr[i-1,j-1]+arr[i-1,j]+arr[i-1,j+1]+
                      arr[i,j]+arr[i+1,j-1]+arr[i+1,j]+arr[i+1,j+1])
    print(sum)
    return max(sum)

In [23]:
result=hourglassSum(arr)
print(result)

1 1
1 2
1 3
1 4
2 1
2 2
2 3
2 4
3 1
3 2
3 3
3 4
4 1
4 2
4 3
4 4
[1, 14, -7, -19, -10, -9, 2, 4, -17, 7, -4, -13, -30, -23, 2, 9]
14


In [24]:
sum = []
def hourglassSum(arr):
     
    for i in range(1,5):
        for j in range(1,5):
            sum.append(arr[i-1][j-1]+arr[i-1][j]+arr[i-1][j+1]+
                      arr[i][j]+arr[i+1][j-1]+arr[i+1][j]+arr[i+1][j+1])
    return max(sum)

In [25]:
result=hourglassSum(arr)
print(result)

14


In [29]:
arr2=np.random.randint(1,4,3)

In [30]:
arr2

array([1, 3, 3])

In [31]:
len(arr2)

3

In [32]:
for i in range(3,5,1):
    print(i)

3
4


In [40]:
def  oddNumbers(l, r):
    
    odd_num=[]
    for i in range(l,r+1,1):
        if i%2!=0:
            odd_num.append(i)
    return odd_num

In [41]:
o=oddNumbers(4,6)

In [42]:
print(o)

[5]


array size a, left rotation d

performed on array [1,2,3,4,5] , then the array would become [3,4,5,1,2].

Given an array a of n integers and a number, , perform  left rotations on the array. Return the updated array to be printed as a single line of space-separated integers.

In [33]:
def rotLeft(a, d):
    new_array = []   
    for i in range(d,len(a)):
        new_array.append(a[i])
        
    for j in range(0,d):
        new_array.append(a[j])
    return new_array

In [36]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
new_arr = rotLeft(arr,5)
new_arr

[5, 6, 7, 8, 9, 0, 1, 2, 3, 4]

New Year Chaos Problem

It's New Year's Day and everyone's in line for the Wonderland rollercoaster ride! There are a number of people queued up, and each person wears a sticker indicating their initial position in the queue. Initial positions increment by  from  at the front of the line to  at the back.

Any person in the queue can bribe the person directly in front of them to swap positions. If two people swap positions, they still wear the same sticker denoting their original places in line. One person can bribe at most two others. For example, if n=8 and Person4 bribes Person5, the queue will look like this: 1,2,3,5,4,6,7,8.

Fascinated by this chaotic queue, you decide you must know the minimum number of bribes that took place to get the queue into its current state!

In [ ]:
def minimumBribes(q):

In [1]:
def minmaxspicychicken(min,max):
    for i in range(min,max+1):
        if i%3==0 and i%5==0:
            print(i,'SpicyChicken!')
        elif i%3==0:
            print(i,'Spicy')
        elif i%5==0:
            print(i,'Chicken')
        else:
            print(i)

In [2]:
minmaxspicychicken(1,100)

1
2
3 Spicy
4
5 Chicken
6 Spicy
7
8
9 Spicy
10 Chicken
11
12 Spicy
13
14
15 SpicyChicken!
16
17
18 Spicy
19
20 Chicken
21 Spicy
22
23
24 Spicy
25 Chicken
26
27 Spicy
28
29
30 SpicyChicken!
31
32
33 Spicy
34
35 Chicken
36 Spicy
37
38
39 Spicy
40 Chicken
41
42 Spicy
43
44
45 SpicyChicken!
46
47
48 Spicy
49
50 Chicken
51 Spicy
52
53
54 Spicy
55 Chicken
56
57 Spicy
58
59
60 SpicyChicken!
61
62
63 Spicy
64
65 Chicken
66 Spicy
67
68
69 Spicy
70 Chicken
71
72 Spicy
73
74
75 SpicyChicken!
76
77
78 Spicy
79
80 Chicken
81 Spicy
82
83
84 Spicy
85 Chicken
86
87 Spicy
88
89
90 SpicyChicken!
91
92
93 Spicy
94
95 Chicken
96 Spicy
97
98
99 Spicy
100 Chicken


## Queens on Board

You have an N * M chessboard on which some squares are blocked out. In how many ways can you place one or more queens on the board, such that, no two queens attack each other? Two queens attack each other, if one can reach the other by moving horizontally, vertically, or diagonally without passing over any blocked square. At most one queen can be placed on a square. A queen cannot be placed on a blocked square.

### Sample input
4  
3 3  
...  
...  
...  
3 3  
.#.  
.#.  
...  
2 4  
.#..  
....  
1 1  
#

### Sample output

17  
18  
14  
0 

In [ ]:
def queensBoard(board):
    #
    # Write your code here.
    #

In [ ]:
#!/bin/python3

import os
import sys

#
# Complete the queensBoard function below.
#
def queensBoard(board):
    #
    # Write your code here.
    #

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        nm = input().split()

        n = int(nm[0])

        m = int(nm[1])

        board = []

        for _ in range(n):
            board_item = input()
            board.append(board_item)

        result = queensBoard(board)

        fptr.write(str(result) + '\n')

    fptr.close()
